In [1]:
#import library
import pandas as pd
import numpy as np

# Task 1: Calculate the Win Rate

In this task, you need to calculate the win rate of each Pokemon using the battle history. You first import *pokemon.csv* and *battles.csv* as pandas data frames. Then, you create a new column called ‘Win Rate’ in the data frame created from pokemon.csv. The win rate of Pokemon i is defined as follows:

In [2]:
%%latex
$$\text{WinRate}_i = \frac{\# \text{battles that pokemon i wins}}{\# \text{battles that Pokemon i is involved}}$$

In [3]:
# import both csvs
pkdf = pd.read_csv('./pokemon.csv', sep=',', index_col="#")
btdf = pd.read_csv('./battles.csv', sep=',')

In [4]:
pkdf

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Has Gender,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,True,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,True,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,True,False
4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,True,False
5,Charmander,Fire,NaN,39,52,43,60,50,65,1,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,False,True
797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,False,True
798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,False,True
799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,False,True
800,Volcanion,Fire,Water,80,110,120,130,90,70,6,False,True

In [5]:
# here we confirm no two same pokemon has battled, so total battle count can simply add two
print ('Is there have no same pokemon battled together?', btdf[ btdf['First_pokemon'] == btdf['Second_pokemon'] ].shape[0] == 0)

Is there have no same pokemon battled together? True

In [6]:
# define count function
def winCount():
    return btdf['Winner'].value_counts().sort_index()

def totalBattleCount():
    return btdf['First_pokemon'].value_counts().sort_index() + btdf['Second_pokemon'].value_counts().sort_index()

In [7]:
# define win rate function
def addWinRate():
    win = winCount()
    total = totalBattleCount()
    return win.div(total)

In [8]:
pkdf['WinRate'] = addWinRate()

In [9]:
pkdf

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Has Gender,Legendary,WinRate
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,True,False,0.254902
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,True,False,0.395833
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,True,False,0.631068
4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,True,False,0.578947
5,Charmander,Fire,NaN,39,52,43,60,50,65,1,True,False,0.445652
...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,False,True,0.386364
797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,False,True,0.911765
798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,False,True,0.528090
799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,False,True,0.617886
800,Volcanion,Fire,Water,80,110,120,130,90,70,6,False,True,0.602151

In [10]:
pkdf.to_csv('./pokemon.csv', header=True)